USE master
GO
IF DB_ID('QL_HOADON') IS NOT NULL
	DROP DATABASE QL_HOADON
GO
CREATE DATABASE QL_HOADON
GO
USE QL_HOADON
GO

CREATE TABLE KhachHang
(
	MaKH CHAR(6),
	Ho NVARCHAR(10),
	Ten NVARCHAR(10),
	NgSinh DATETIME,
	SoNha INT,
	Duong NVARCHAR(20),
	Phuong NVARCHAR(20),
	Quan NVARCHAR(20),
	TPho NVARCHAR(20),
	DThoai CHAR(10)
	CONSTRAINT PK_KH
	PRIMARY KEY(MaKH)
)

CREATE TABLE HoaDon
(
	MaHD CHAR(6),
	MaKH CHAR(6),
	NgayLap DATETIME,
	TongTien INT
	CONSTRAINT PK_HD
	PRIMARY KEY(MaHD)
)

CREATE TABLE CT_HoaDon
(
	MaHD CHAR(6),
	MaSP CHAR(6),
	SoLuong INT,
	GiaBan INT,
	GiaGiam INT,
	ThanTien INT
	CONSTRAINT PK_CTHD
	PRIMARY KEY(MaHD, MaSP)
)

CREATE TABLE SanPham
(
	MaSP CHAR(6),
	TenSP NVARCHAR(20),
	SoLuongTon INT,
	MoTa NVARCHAR(50),
	Gia INT
	CONSTRAINT PK_SP
	PRIMARY KEY(MaSP)
)

ALTER TABLE HoaDon
ADD
	CONSTRAINT FK_HD_KH
	FOREIGN KEY(MaKH)
	REFERENCES KhachHang

ALTER TABLE CT_HoaDon
ADD
	CONSTRAINT FK_CTHD_HD
	FOREIGN KEY(MaHD)
	REFERENCES HoaDon

ALTER TABLE CT_HoaDon
ADD
	CONSTRAINT FK_CTHD_SP
	FOREIGN KEY(MaSP)
	REFERENCES SanPham


CREATE TABLE NGUOIDUNG
(
	TENDANGNHAP CHAR(20),
	MATKHAU CHAR(20)

	CONSTRAINT PK_NGUOIDUNG PRIMARY KEY(TENDANGNHAP,MATKHAU)
)

INSERT INTO NGUOIDUNG VALUES('THINHNGUYEN','123456')
